// Temporary development stub for contract generation
// This file provides a simple deterministic response so the frontend can
// continue to function while the real backend route is restored.
// Remove or replace this with the production implementation when ready.

import type { NextApiRequest, NextApiResponse } from 'next';

function escapeHtml(s: any) {
  if (s === null || s === undefined) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const payload = req.body || {};
    const { type = 'contract', parties = [], jurisdiction, effectiveDate, clauses = [] } = payload;

    const title = escapeHtml(payload.title || `${type.toString().toUpperCase()} Agreement`);
    const partyList = Array.isArray(parties) ? parties.filter(Boolean) : [];

    // Build simple HTML contract
    let html = `<h1>${title}</h1>`;
    html += `<p><strong>Type:</strong> ${escapeHtml(type)}</p>`;
    if (partyList.length) html += `<p><strong>Parties:</strong> ${escapeHtml(partyList.join(' | '))}</p>`;
    if (jurisdiction) html += `<p><strong>Jurisdiction:</strong> ${escapeHtml(jurisdiction)}</p>`;
    if (effectiveDate) html += `<p><strong>Effective Date:</strong> ${escapeHtml(effectiveDate)}</p>`;

    if (Array.isArray(clauses) && clauses.length) {
      html += '<h2>Clauses</h2><ol>';
      for (let i = 0; i < clauses.length; i++) {
        const c = clauses[i];
        const text = typeof c === 'string' ? c : (c && c.text) ? c.text : '';
        html += `<li>${escapeHtml(text)}</li>`;
      }
      html += '</ol>';
    } else {
      html += '<p><em>No clauses provided. This is a placeholder contract generated by a local stub.</em></p>';
    }

    // Provide a normalized-ish response shape similar to what the frontend expects
    const resp = {
      contractText: html,
      isHtml: true,
      warnings: [],
      references: [],
    };

    return res.status(200).json(resp);
  } catch (err: any) {
    console.error('generateContract stub error:', err);
    return res.status(500).json({ error: 'Internal server error' });
  }
}
